@startuml
skinparam backgroundColor #FFFFFC
title 查询聚合页
actor 用户 #red


用户 -> 购物端APP : 点击banner进入聚合页
购物端APP -> 骑手商城后端 : 查看聚合页
note right
入参：
1、聚合页id
end note
骑手商城后端 -> 骑手商城后端 : 渠道判断
骑手商城后端 --> 购物端APP : 渠道不匹配，返回数据给前端
骑手商城后端 -> 骑手商城后端 : 查询数据
note right
查询结果数据：
1、聚合页id
2、聚合页名称
3、商品词性与词性内容
4、营销位json
end note

骑手商城后端 -> 购物端APP : 结果数据返回
note right
结果数据：
1、聚合页id
2、聚合页名称
3、商品词性与词性内容
4、营销位json
end note

购物端APP -> 购物端APP : 判断词性类型

alt 判断词性类型

else 词性类型为自定义商品id
    购物端APP -> 购物端APP : 获取聚合页中配置的商品ids
    note right : 词性内容就是商品ids
    购物端APP -> 骑手商城后端 : 召回商品ids（召回类型:通过商品ids批量召回）
    note right : 召回主要是过滤非线上、非匹配渠道、非匹配城市的商品id

else 词性类型为平台券可用商品
    购物端APP -> 骑手商城后端 : 通过平台优惠劵活动id获取优惠劵活动页
    note right : 词性内容就是平台优惠劵活动id
    骑手商城后端 --> 购物端APP : 返回领取页数据
    note right : 商品id列表与优惠劵列表
    alt 词性类型为平台券可用商品
    else 优惠劵活动优惠券范围为全平台
        购物端APP -> 购物端APP : 获取优惠劵可用的商品id是空list
        购物端APP -> 骑手商城后端 : 召回商品ids（召回类型:全局搜索）
    else 优惠劵活动优惠券范围为后台类目
        购物端APP -> 购物端APP : 获取优惠劵可用的商品id是后台通过类目召回的
        note right : 商品id列由后端召回（可直接使用）
    else 优惠劵活动优惠券范围为自定义商品id
        购物端APP -> 购物端APP : 获取优惠劵可用的商品id是后台配置的数据
        note right : 商品id列表需要过滤（不可直接使用）
        购物端APP -> 骑手商城后端 : 召回商品ids（召回类型:通过商品ids批量召回）
        note right : 召回主要是过滤非线上、非匹配渠道、非匹配城市的商品id
    end

else 词性类型为画像
    购物端APP -> 购物端APP : 获取聚合页中配置的画像id
    购物端APP -> 骑手商城后端 : 召回商品ids（召回类型:画像召回）
    骑手商城后端 -> 骑手商城后端 : 查询画像对应的商品ids
    骑手商城后端 -> 商品中心 : 商品ids召回可匹配的商品
    note right : 召回主要是过滤非线上、非匹配渠道、非匹配城市的商品id
end

par 获取商品列表
购物端APP -> 购物端APP : 通过已召回的商品ids请求商品列表
购物端APP -> 购物端APP : 分批商品ids（20一批）
购物端APP -> 骑手商城后端 : 分批请求商品列表（接口复用）
骑手商城后端 -> 购物端APP : 返回商品列表
end


@enduml