@startuml
skinparam backgroundColor #FFFFFC
title 在线客服按钮入口控制
actor 用户 #red

alt 商品详情页 case
用户 -> 前端 : 商品详情
前端 -> 骑手商城服务端 : 获取是否能IM
骑手商城服务端 -> 到综IM : 获取店铺IM开关与店铺聊天室链接
note right
入参：
1、供应商id
2、类型：商品
3、spuId
end note
到综IM --> 骑手商城服务端 : 返回开关与入口链接
骑手商城服务端 --> 前端 : 控制按钮是否展示与入口按钮链接

else 店铺详情页
用户 -> 前端 : 店铺详情页
前端 -> 骑手商城服务端 : 获取是否能IM
骑手商城服务端 -> 到综IM : 获取店铺IM开关与店铺聊天室链接
note right
入参：
1、供应商id
2、类型：店铺
3、暂定
end note
到综IM --> 骑手商城服务端 : 返回开关与入口链接
骑手商城服务端 --> 前端 : 控制按钮是否展示与入口按钮链接


else 订单详情页

用户 -> 前端 : 订单详情页
前端 -> 骑手商城服务端 : 获取是否能IM
骑手商城服务端 -> 到综IM : 获取店铺IM开关与店铺聊天室链接
note right
入参：
1、供应商id
2、类型：订单
3、orderId
end note
到综IM --> 骑手商城服务端 : 返回开关与入口链接
骑手商城服务端 --> 前端 : 控制按钮是否展示与入口按钮链接

end

@enduml