@startuml
skinparam backgroundColor #FFFFFC
title 聊天室功能交互
actor 用户 #red
== 聊天室进入 ==

用户 -> 骑手商城前端 : 1、进入聊天室
骑手商城前端 -> 到综IM系统 : 携带链接跳转到聊天室
到综IM系统 -> 到综IM系统 : 通过token获取passportId
到综IM系统 -> 骑手商城后端 : 通过passportId获取banmaUserId
骑手商城后端 --> 到综IM系统 : 返回banmaUserId
到综IM系统 -> 到综IM系统 : 获取供应商欢迎语
到综IM系统 -> 骑手商城后端 : 获取供应商信息
note right : 入参：供应商id
骑手商城后端 --> 到综IM系统 : 返回供应商头像、名称
到综IM系统 -> 骑手商城后端 : 获取用户信息
note right : 入参：banmaUserId
骑手商城后端 --> 到综IM系统 : 返回用户头像、名称

alt 商品详情页
到综IM系统 -> 骑手商城后端 : 获取商品卡片信息（SPI）
note right
入参：
1、spuId
end note
骑手商城后端 --> 到综IM系统 : 返回商品头图、商品名称、商品价格

else 店铺详情页
到综IM系统 -> 到综IM系统 : 不需要展示卡片

else 订单详情页
到综IM系统 -> 骑手商城后端 : 获取订单卡片信息（SPI）
note right
入参：
1、orderId
end note
骑手商城后端 --> 到综IM系统 : 返回订单中首个商品头图和商品名称，以及订单共多少个商品，合计支付价格，保留两位小数

end

到综IM系统 -> 到综IM系统 : 获取消息状态
到综IM系统 -> 到综IM系统 : 组装消息返回展示

到综IM系统 -> 骑手商城后端 : 获取跳转链接（SPI）
note right
入参：
1、订单详情:orderId
2、商品详情:spuId
3、店铺详情:providerId
end note
骑手商城后端 --> 到综IM系统 : 返回对应的链接


== 获取历史消息 ==
到综IM系统 -> 骑手商城后端 : 获取供应商信息与用户信息
到综IM系统 -> 到综IM系统 : 获取消息列表展示

== 发送消息 ==
到综IM系统 -> 骑手商城后端 : 获取供应商信息与用户信息
到综IM系统 -> 骑手商城后端 : 获取卡片信息（SPI）
到综IM系统 -> 到综IM系统 : 发送消息（包括风控过滤）
到综IM系统 -> 到综IM系统 : 实时推送
到综IM系统 -> 到综IM系统 : 离线MQ推送
note right:业务方待定是否使用


== 拉黑 ==
到综IM系统 -> 到综IM系统 : 拉黑

== 获取店铺商品卡片 ==
到综IM系统 -> 骑手商城后端 : 获取店铺下商品卡片（SPI）
到综IM系统 -> 到综IM系统 : 展示商品卡片列表

@enduml