@startuml
skinparam backgroundColor #FFFFFC
title 券列表&劵活动撤销
actor 运营 #red

运营 -> 烽火台前端 : 劵列表查询
烽火台前端 -> 烽火台前端 : 前端逻辑校验
note right:参数类型校验
烽火台前端 -> 骑手商城服务端 : 劵列表查询
note right
参数：
1、活动id（劵平台的活动id，非我们DB的主键）
2、活动名称
3、劵类型
4、销售渠道
5、活动状态 （支持聚合页接口复用）
end note
骑手商城服务端 -> 骑手商城服务端 : 后端参数校验
骑手商城服务端 -> DB : 搜索列表
DB -> 骑手商城服务端 : 返回列表
骑手商城服务端 -> 数据组 : 获取劵的使用情况
note right:每种满减劵对应的：发放数量，领取数量，使用数量
骑手商城服务端 -> 骑手商城服务端 : 组装vo

骑手商城服务端 -> 烽火台前端 : 返回列表
note right:可展示的按钮控制返回

运营 -> 烽火台前端 : 撤销活动
烽火台前端 -> 骑手商城服务端 : 撤销活动
骑手商城服务端 -> 骑手商城服务端 : 校验状态是否可撤销
骑手商城服务端 -> 劵平台 : 更新活动状态为已撤销（需要支持幂等）
骑手商城服务端 -> DB : 更新DB状态为已撤销
骑手商城服务端 -> 烽火台前端 : 返回更新结果

运营 -> 烽火台前端 : 查询活动详情
烽火台前端 -> 骑手商城服务端 : 查询活动详情
骑手商城服务端 -> DB : 查询活动详情
DB -> 骑手商城服务端 : 返回活动详情
骑手商城服务端 -> 烽火台前端 : 返回活动详情


@enduml