@startuml
skinparam backgroundColor #FFFFFC
title 券活动更新/创建
actor 运营 #red

运营 -> 烽火台前端 : 券活动更新/创建
alt 辅助接口
烽火台前端 -> 骑手商城服务端 : 获取后台类目列表接口
烽火台前端 -> 骑手商城服务端 : 判断商品id是否为有效商品
note right : 新增是否是预售模式，校验预售商品不能配置优惠劵（填下spu处用于校验商品合理性）
烽火台前端 -> 骑手商城服务端 : 获取基础枚举
end

烽火台前端 -> 烽火台前端 : 前端逻辑校验
note right:产品需要限制的地方都需要校验
烽火台前端 -> 骑手商城服务端 : 券活动更新/创建
note right : 更新活动id>0,新增活动id=0（活动id为劵返回的活动id）
骑手商城服务端 -> 骑手商城服务端 : 后端逻辑校验
note right
校验逻辑:
1、活动名称长度,不能重复
2、活动预算
3、活动时间，劵时间
4、劵范围对应的选项限制
5、券金额/数量 限制
6、每人限领数
7、下发用户限制
8、优惠劵数量与下发用户数量对比限制
9、使用说明 限制
10、待开始可全部修改（劵配置不能更新），进行中，可修改活动结束时间；
11、预售商品不支持劵（系统与平台劵）
end note

骑手商城服务端 -> 劵平台 : 券活动更新/创建
note right:具体接口待定（劵的活动id标识更新还是新增）
劵平台 -> 骑手商城服务端 : 返回更新结果
骑手商城服务端 -> 骑手商城服务端 : 更新存储数据
note right:所有的劵配置信息、骑手商城都会存储
骑手商城服务端-> 烽火台前端 : 返回更新结果


@enduml