@startuml
skinparam backgroundColor #FFFFFC
title 查询聚合页
actor 用户 #red


用户 -> 购物端APP : 点击banner进入聚合页
购物端APP -> 骑手商城后端 : 查看聚合页
note right
入参：
1、聚合页id
end note
骑手商城后端 -> 骑手商城后端 : 查询数据
note right
查询结果数据：
1、聚合页id
2、聚合页名称
3、商品词性与词性内容
4、营销位json
end note

alt 判断词性类型
else 词性类型为自定义商品id
骑手商城后端 -> 骑手商城后端 : 保持原逻辑
note right : 词性内容就是商品ids
else 词性类型为平台券可用商品
    alt 词性类型为平台券可用商品
    else 优惠劵活动优惠券范围为全平台
        骑手商城后端 -> 骑手商城后端 : 新增商品ids扩展字段spuIds&&spuIds为空list
        note right : 注意点（商品ids为空list）
    else 优惠劵活动优惠券范围为后台类目
        骑手商城后端 -> 商品中心 : 根据后台类目ids获取类目对应的商品ids，并赋值到新增的扩展字段spuIds
        note right : 商品中心是否能支持？
        商品中心 ->   骑手商城后端: 返回商品spuIds
    else 优惠劵活动优惠券范围为自定义商品id
        骑手商城后端 -> 骑手商城后端 : 获取优惠劵配置内容中的商品ids赋值到新的spuIds字段返回
    end
end

骑手商城后端 -> 购物端APP : 结果数据返回
note right
结果数据：
1、聚合页id
2、聚合页名称
3、商品词性与词性内容
4、营销位json
5、扩展商品ids字段spuIds
end note

par 获取商品列表
购物端APP -> 购物端APP : 通过配置的商品ids请求商品列表

alt 判断商品ids是否为空&&聚合页词性
    else 聚合页词性为平台券可用商品&&词性内容中的扩展字段spuIds为空list
    购物端APP -> 骑手商城后端 : 通过通用的首页召回商品ids方式召回
    else 其他场景
    购物端APP -> 骑手商城后端 : 将使用返回的商品spuIds获取排序逻辑
    end
    骑手商城后端 -> 商品中心 : 召回排序商品ids
note right
入参：
1、排序逻辑：销量与第一次上架时间
2、商品ids (分场景)
3、销售渠道 （过滤条件）
4、销售城市 （过滤条件）
end note
商品中心 -> 骑手商城后端 : 返回排序的商品ids
note right
结果：（最好与召回商品ids接口一致）
1、门店id（需要）
2、商品id （需要）
end note
骑手商城后端 -> 购物端APP : 返回排序的商品ids
购物端APP -> 购物端APP : 分批商品ids（20一批）
购物端APP -> 骑手商城后端 : 分批请求商品列表（接口复用）
骑手商城后端 -> 购物端APP : 返回商品列表
购物端APP -> 用户 : 展示商品列表

end

par 获取优惠劵列表
购物端APP -> 购物端APP : 获取聚合页中词性内容
购物端APP -> 骑手商城后端 : 通过优惠劵活动id获取优惠劵列表
骑手商城后端 -> 骑手商城后端 : 取出活动中配置的优惠劵id
骑手商城后端 -> 劵平台 : 批量获取优惠劵列表
note right
入参:
1、优惠劵ids
2、用户信息
end note
劵平台 -> 骑手商城后端 : 返回优惠劵列表
note right
结果vo对象:
1、优惠劵id
2、劵的状态(可用未领取、可用已领取、已抢光、已失效)
3、劵的满减信息
4、劵的领取时间范围
5、劵的可使用时间范围
end note
骑手商城后端 -> 购物端APP:返回结果

end



购物端APP -> 购物端APP : 加工营销位json展示
购物端APP -> 用户 : 展示聚合配置信息
@enduml