@startuml
skinparam backgroundColor #FFFFFC
title 订单预览
actor 用户 #red

用户 -> 购物端APP: 订单预览
note right
勾选数据（商品拥有的劵情况，商品金额100）:
1、店铺A商品A (店铺A店铺劵101满100减10 3张，店铺劵110 满100减20 1张，平台优惠劵901（满90减10）& 902（满100减10）& 903（满80减10）个一张)
2、店铺B商品B (店铺B店铺劵102满100减10 3张，平台优惠劵901，902 各一张)
3、店铺C商品C (店铺C店铺劵103满100减10 3张，平台优惠劵902，903 各一张)
end note
购物端APP -> 骑手商城服务端 : 订单预览
骑手商城服务端 -> 骑手商城服务端 : 销售城市校验
骑手商城服务端 -> 骑手商城服务端 : 销售渠道校验

骑手商城服务端 -> 订单中心 : 订单预览
note right
核心新增入参:
第一次请求会可能会带入店铺优惠劵id&平台优惠劵id
<b>购物车可能会带来
end note

订单中心 -> 活动中心 : 获取折扣信息与店铺推荐劵信息&门槛信息
活动中心 -> 劵平台 : 获取店铺推荐劵信息&门槛信息
活动中心 --> 订单中心 : 返回折扣信息与店铺推荐劵信息&门槛信息
订单中心 -> 骑手商城服务端 : 返回折扣信息与店铺推荐劵信息&门槛信息
note right
结果结果（店铺A举例）：
1、使用店铺推荐劵之后的门槛 <b>门槛：80
2、平台优惠的总金额
3、总的实付金额会加入平台优惠的变化
4、店铺推荐劵 ：店铺劵110 满100减20
end note

骑手商城服务端 -> 劵平台 : 通过商品Sku与用户与门槛获取用户可使用的平台优惠劵与店铺劵列表
note right : <b>门槛：80
劵平台 --> 骑手商城服务端: 返回劵列表
note right
结果（店铺A举例）:
1、平台优惠劵 903（满80减10）
2、店铺A店铺劵101满100减10 3张，店铺劵110 满100减20 1张
end note

骑手商城服务端 -> 骑手商城服务端 : 劵需要过滤销售渠道
骑手商城服务端 -> 骑手商城服务端 : 组装信息返回
骑手商城服务端 -->购物端APP : 组装信息返回
note right
结果：
1、店铺A商品A (店铺A店铺劵101满100减10 3张，店铺劵110 满100减20 1张，平台优惠劵903)
2、店铺B商品B (店铺B店铺劵101满100减10 3张，平台优惠劵902)
3、店铺C商品C (店铺C店铺劵101满100减10 3张，平台优惠劵902，903)
end note
用户 -> 购物端APP: 选择店铺A商品A中平台劵903
购物端APP -> 骑手商城服务端 : 带着店铺A商品A中的平台劵903 请求获取计算费用

骑手商城服务端 -> 订单中心 : 获取数据
note right
核心新增入参:
店铺A商品A中的平台劵903,店铺劵110
end note

订单中心 -> 活动中心 : 获取费用
活动中心 -> 劵平台 : 使用平台劵计算费用
活动中心 --> 订单中心 : 返回费用
订单中心 --> 骑手商城服务端 : 返回订单信息
note right : 订单中心返回是需要考虑劵不可用是返回的异常（已使用&已过期）
骑手商城服务端 -->购物端APP : 组装信息返回
购物端APP -> 购物端APP: 优惠券被其他店铺占用场景处理
note right :店铺B商品B 中的平台劵903 置为暂不可用，购物车其他订单占用



用户 -> 购物端APP: 放弃选择店铺A商品A中平台劵903
购物端APP -> 骑手商城服务端 : 重新请求（不带平台劵id）
骑手商城服务端 -> 购物端APP : 返回数据
购物端APP -> 购物端APP : 不可用变为可用状态场景
note right :店铺B商品B 中的平台劵903 置为可用


@enduml