@startuml
skinparam backgroundColor #FFFFFC
title 优惠劵领取页
actor 用户 #red

用户 -> 购物端APP : 点击banner进入优惠劵领取页
购物端APP -> 骑手商城后端 : 查看优惠劵领取页
note right
入参：
1、活动id
end note
骑手商城后端 -> 骑手商城后端 : 查询数据
note right
核心数据：
1、活动id
2、优惠劵ids
3、优惠劵配置的类型
4、优惠劵配置的类型对应的内容
5、渠道
end note


alt 优惠劵配置的类型
else 优惠劵活动优惠券范围为全平台
    骑手商城后端 -> 骑手商城后端 : 新增商品ids扩展字段spuIds&&spuIds为空list
    note right : 注意点（商品ids为空list）
else 优惠劵活动优惠券范围为后台类目
    骑手商城后端 -> 商品中心 : 根据后台类目ids获取类目对应的商品ids，并赋值到新增的扩展字段spuIds
    商品中心 ->   骑手商城后端: 返回商品spuIds
else 优惠劵活动优惠券范围为自定义商品id
    骑手商城后端 -> 骑手商城后端 : 获取优惠劵配置内容中的商品ids赋值到新的spuIds字段返回
end


骑手商城后端 -> 劵平台 : 通过优惠劵id获取优惠劵列表
劵平台 -> 骑手商城后端: 返回对应列表

骑手商城后端 -> 骑手商城后端: 组装vo(排序优惠劵顺序（多张券按照优惠金额的幅度由大到小进行排序；幅度一致，判断距离优惠券过期的远近，由近到远进行排序；）)
note right
核心结果:
1、优惠劵列表
2、商品ids
3、背景图
4、优惠券标题+利益点描述
end note
骑手商城后端 -> 购物端APP: 返回数据
@enduml