@startuml
skinparam  shadowing false
skinparam usecase {
'BackgroundColor white
'BorderColor black

'BackgroundColor<< Main >> YellowGreen
'BorderColor<< Main >> YellowGreen

'ArrowColor black
'ActorBorderColor black
'ActorFontName Courier

'ActorBackgroundColor<< user >> black
}
left to right direction


购物端功能 --> (聚合页) : 接口需改造
(聚合页) <.. (获取聚合页) : 内部接口-接口需改造
(聚合页) <.. (获取优惠劵活动配置) : 内部接口-新增
(聚合页) <.. (商品中心-后台类目ids批量获取所有spuids) : 商品中心接口-接口需改造
(聚合页) <.. (卷平台-优惠劵id批量获取优惠劵列表) : 劵平台接口-新增


购物端功能 --> (获取待弹窗优惠劵列表) : 接口新增
note right : 优惠劵列表与商品列表逻辑参考聚合页
(获取待弹窗优惠劵列表) <.. (缓存) : 内部接口-新增


购物端功能 --> (领取页) : 接口新增
note right : 优惠劵列表与商品列表逻辑参考聚合页
(领取页) <.. (获取优惠劵活动配置) : 内部接口-新增


购物端功能 --> (可以商品列表) : 老接口

购物端功能 --> (我的优惠劵) : 接口需改造
(我的优惠劵) <.. (劵平台-我的优惠劵) : 接口需改造


购物端功能 --> (店铺优惠劵) : 接口需改造
(店铺优惠劵) <.. (劵平台-店铺优惠劵) : 接口需改造

购物端功能 --> (商品优惠劵) : 接口需改造
(商品优惠劵) <.. (劵平台-商品优惠劵) : 接口需改造

购物端功能 --> (购物车) : 接口需改造
(购物车) <.. (购物车-商品勾选与更新) : 接口需改造

购物端功能 --> (订单预览) : 接口需改造
(订单预览) <.. (订单中心-订单预览支持平台劵) : 接口需改造

购物端功能 --> (订单提交) : 接口需改造
(订单提交) <.. (订单中心-订单提交支持平台劵) : 接口需改造

购物端功能 --> (订单列表&订单详情) : 接口需改造
(订单列表&订单详情) <.. (订单中心-订单列表&订单详情支持平台劵) : 接口需改造

@enduml