@startuml
skinparam backgroundColor #FFFFFC
title 优惠劵状态处理

骑手商城前端 -> 骑手商城后端 :获取优惠劵列表
骑手商城后端 -> 劵平台 : 获取优惠劵列表
note right
入参:
1、用户
2、优惠劵ids
end note


劵平台 -> 骑手商城后端 : 返回优惠劵信息
note right
结果:
1、优惠劵id
2、活动id
3、劵的状态(未使用、已过期、已使用) && 劵的领取状态（可领取、不可领取、已抢光）
    --只要有未使用的优先返回未使用，其次已使用，最后已过期
    --可领取的定义：优惠劵可领时间满足，个人限购满足
    --不可领取定义：时间不满足 或者 个人限购不满足
    --已抢光的定义：总优惠劵不满足
4、劵的满减信息
5、劵的领取时间
    --最后一次领取时间
6、活动的可领时间范围
7、用户已领券的可用时间范围
    --所有时间最早-最晚的时间范围
8、优惠劵类型（平台、品类、指定商品、店铺）
9、优惠劵类型对应的配置内(类目id，商品id，skuid)
10、优惠劵对应的销售渠道
11、用户已领优惠劵数据量
12、用户限领数据
end note

骑手商城后端 -> 骑手商城前端 : 返回优惠劵信息
骑手商城前端 -> 骑手商城前端 : 卡片样式
alt 优惠劵卡片展示逻辑
    par 活动未开始
        else 活动未开始
        骑手商城前端 -> 骑手商城前端 : 未开始
    end
    par 活动进行中
        else 可领取
        骑手商城前端 -> 骑手商城前端 : 立即领取
        else 可领取&未使用&未到可用时间
        骑手商城前端 -> 骑手商城前端 : 查看可用商品
        else 可领取&未使用&已到可用时间
        骑手商城前端 -> 骑手商城前端 : 去使用
        else 可领取&已过期
        骑手商城前端 -> 骑手商城前端 : 立即领取
        else 可领取&已使用
        骑手商城前端 -> 骑手商城前端 : 立即领取
        else 不可领取&已使用
        骑手商城前端 -> 骑手商城前端 : 已使用
        else 不可领取&已过期
        骑手商城前端 -> 骑手商城前端 : 已过期
        else 已抢光
        骑手商城前端 -> 骑手商城前端 : 已抢光
    end
    par 活动结束
        else 未使用&未到可用时间
        骑手商城前端 -> 骑手商城前端 : 查看可用商品
        else 未使用&已到可用时间
        骑手商城前端 -> 骑手商城前端 : 去使用
        else 已过期
        骑手商城前端 -> 骑手商城前端 : 已过期
        else 已使用
        骑手商城前端 -> 骑手商城前端 : 已使用
    end


end

@enduml